DATASET_PATH = "/home/microway/Arman/xapp/colosseum-oran-coloran-dataset/rome_static_medium"
WANDB_API_KEY = ""

types_columns = {
    "Timestamp": "time",
    "num_ues": "int64",
    "RNTI": "string",
    "IMSI": "string",
    "slice_id": "category",
    "slice_prb": "int64",
    "power_multiplier": "int64",
    "scheduling_policy": "category",
    "dl_mcs": "float64",
    "dl_n_samples": "float64",
    "dl_buffer [bytes]": "int64",
    "tx_brate downlink [Mbps]": "float64",
    "tx_pkts downlink": "int64",
    "tx_errors downlink (%)": "float64",
    "dl_cqi": "int64",
    "ul_mcs":"float64",
    "ul_n_samples": "float64",
    "ul_buffer [bytes]": "int64",
    "rx_brate uplink [Mbps]": "float64",
    "rx_pkts uplink":  "int64",
    "rx_errors uplink (%)": "float64",
    "ul_rssi": "float64",
    "ul_sinr": "float64",
    "phr": "float64",
    "sum_requested_prbs": "float64",
    "sum_granted_prbs": "float64",
    "dl_pmi": "float64",
    "dl_ri": "float64",
    "ul_n": "float64",
    "ul_turbo_iters": "float64",
    "latency_avg_ms": "float64",
    "interarrivals_avg_ms": "float64",
    "app_tx_brate_downlonk_Mbps": "float64",
    "loss_perc": "float64"
}

variable_description = {
    "Timestamp": " UNIX Timestamp",
    "num_ues": "Number of the UEs connected to the cell",
    "IMSI": "IMSI of the UE (primary key with time)",
    "RNTI": "RNTI of the UE",
    "slice_id": "Slice ID the UE belongs to (0 for uRRLC, 1 for eMBB)",
    "slice_prb": "Number of PRBs in the slice",
    "power_multiplier": "Power Multiplier (TBC)",
    "scheduling_policy": "Scheduling policy (0 for RR, 2 is Proportional fair)",
    "dl_mcs": "Downlink MCS",
    "dl_n_samples": "Downlink number of TBC",
    "dl_buffer [bytes]": "Size of the downlink buffer in bytes",
    "tx_brate downlink [Mbps]": "Transmission bitrate in Mbps",
    "tx_pkts downlink": "Number of transmitted packets in downlink",
    "tx_errors downlink (%)": "Percentage of transmission errors in Downlink",
    "dl_cqi": "Downlink Channel Quality Indicator (CQI)",
    "ul_mcs": "Number of MCS in uplink",
    "ul_n_samples": "Uplink number of TBC",
    "ul_buffer [bytes]": "Size of thew uplink buffer",
    "rx_brate uplink [Mbps]": "Receive bitrate in Uplink in Mbps",
    "rx_pkts uplink": "Number of received packet in uplink",
    "rx_errors uplink (%)": "Percentage of RX errors in uplink",
    "ul_rssi": "Uplink RSSI",
    "ul_sinr": "Uplink SINR",
    "phr": "UE Power Headroom Reported (PHR)",
    "sum_requested_prbs": "Sum of the requested PRBs",
    "sum_granted_prbs": "Sum of the granted PRBs",
    "dl_pmi": "Downlink PMI",
    "dl_ri": "Downlink RI",
    "ul_n": "Uplink N",
    "ul_turbo_iters": "Uplink turbo iterations",
    "latency_avg_ms": "Average latency in ms",
    "interarrivals_avg_ms": "Average time of interarrival",
    "app_tx_brate_downlonk_Mbps": "Application transmitted birate downlink in Mbps",
    "loss_perc": "Percentage loss",
}

useless_columns = ['slicing_enabled', 'power_multiplier', 'tx_errors downlink (%)', 'ul_rssi', 'dl_pmi', 'dl_ri', 'ul_n' ]

meta_columns = ['Timestamp','IMSI','RNTI', 'slice_id']

columns_reward = ["tx_brate downlink [Mbps]"]
columns_action = ["slice_prb", "scheduling_policy"]
columns_state = [
    "num_ues",
    "slice_prb",
    "dl_mcs",
    "dl_n_samples",
    "dl_buffer [bytes]",
    "tx_brate downlink [Mbps]",
    "tx_pkts downlink",
    "dl_cqi",
    "ul_mcs",
    "ul_n_samples",
    "ul_buffer [bytes]",
    "rx_brate uplink [Mbps]",
    "rx_pkts uplink",
    "rx_errors uplink (%)",
    "ul_sinr",
    "phr",
    "sum_requested_prbs",
    "sum_granted_prbs",
    "ul_turbo_iters"
]
